maxrice search with loop
ivandubrouski/AQA-av.by pull request #1
Opened 2022-12-05 08:38 UTC by ivandubrouski

2022-12-07 12:37 UTC, NikitaRadzkov commented on playwright-report/index.html
> +window.playwrightReportBase64 = "data:application/zip;base64,UEsDBBQAAAgIADuZhlWd4XZfzQkAAFlNAAAZAAAAYzBhZTk2ZDM5ZDYxMzZiMmI3MjYuanNvbu1c3W7jxhV+FUJYwHIh0/NPjgovkBQtNkAaLIptL2o7BiWNbdYUKZDUeo2tgaC96a
Add this folder in git ignore

2022-12-07 12:54 UTC, NikitaRadzkov requested changes

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/test1.spec.ts
> +import { test, expect } from "@playwright/test";
Remove this extra file

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +    await page.locator(".paging__button").click();
Fix your test. This loop doesn't work. Need add wait for visible element

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-simple.spec.ts
> +  const maxPriceFromList = await page
Don't chain like this. Separate line after first methode 
```javascript
await page.locator(".listing-item__priceusd")
  .nth(0)
  .innerText();
```

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +  await page.goto("https://av.by/");
Add variable with AV url. And use that `const` in tests

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +  await expect(page).toHaveURL("https://av.by/");
Use varible with url here

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +  await page.locator("input.dropdown__input").type("ford");
Change `.type()` to `.fill()`. Fill method faster and works like `Control + V`

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +  let getMaxPrice = allPrices.map(async (item) => {
It can't be work. Use `.map()` method in
```javascript
  const arrPrices = await Promise.all(allPrices.map(el => el.innerText()))
```

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +  // type name = 'sept'| 'october' |'november';
Remove extra comment

2022-12-07 12:54 UTC, NikitaRadzkov commented on tests/av-by-my.spec.ts
> +  // interface Inum { '1' :"123", '2':'wefwef', '3':'MediaKeyMe'}
Remove extra comment

2022-12-08 10:42 UTC, ivandubrouski commented on tests/av-by-my.spec.ts
> +  // interface Inum { '1' :"123", '2':'wefwef', '3':'MediaKeyMe'}
done

2022-12-08 14:46 UTC, NikitaRadzkov requested changes

2022-12-08 14:46 UTC, NikitaRadzkov commented on playwright-report/index.html
>    </body>
Report still exist. Run this command and push 
```shell
git rm --cached
```

2022-12-08 14:46 UTC, NikitaRadzkov commented on tests/test1.spec.ts
> +import { test, expect } from "@playwright/test";
Rename this file. `test1.spec` looks ugly

2022-12-08 14:46 UTC, NikitaRadzkov commented on tests/test1.spec.ts
> +  let sortedArr = numberArr.sort((a, b) => b - a);
Use `const` variable

2022-12-08 14:46 UTC, NikitaRadzkov commented on tests/test1.spec.ts
> +  let maxPriceFromList = sortedArr[0];
Use `const` variable

2022-12-08 14:46 UTC, NikitaRadzkov commented on tests/test1.spec.ts
> +  // const list = page.locator("div.listing__container div div.listing__items");
Remove this extra comment

2022-12-08 15:21 UTC, NikitaRadzkov approved these changes

2022-12-08 15:22 UTC, merged